name: "Lint"

on:
  push:
    branches: [main,github-actions-test]
  pull_request:
    branches: [main]

jobs:
  black-isort-flake8:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10.11]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Linting
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: install dependencies [pip]
        run:  |
          pip install -e .[dev] --no-deps
      - name : linting [black and isort]
        run: |
          black . --check --extend-exclude 'examples'
          isort --profile black --check .
      - name: linting [flake8]
        run: |
          flake8 topomodelx/ test/
